### ISSUE TITLE
Questions regarding this project

### ISSUE THREAD

**Issue by Joe23232** [ALANVF/star#1]
Hi I have some questions regarding this language:

1. Does it have C interop?
2. Is this a compiled language?
3. Does it have GC/reference counter or does it have the ownership model or something similar/alternative which handles memory during compile time?
4. Does it compile to C code?
5. Does it support multithreading?
6. How does it differ to the Raku  programmign language?

**Comment by ALANVF** [comment]
1) Ideally, yes. I'm planning on targeting LLVM, which would make C interop trivial.
2) Yes.
3) I'm hoping to use a variety of memeory management methods to avoid using a GC as much as possible, such as ownership, automatic reference counting, and Nim-like reference counting to deal with cycles. Do note that these wouldn't be accessible from Star itself, but would rather be inserted by the compiler depending on which method is most convenient for a given value. (More on that later if you'd like).
4) Probably not. I'm planning to bootstrap Star using a VM, and then switch to LLVM (bitcode) once bootstrapped.
5) Ideally it does, however it's not a priority right now. I'm well aware of how important it is to properly implement multithreading and concurrency, but I wouldn't even want to think about it until Star has been switched to LLVM in order to prevent massive breaking changes down the line.
6) It actually differs a lot from Raku. To put it briefly, Star doesn't share many features from Raku, but rather follows the idea of having a lot of (possibly uncommon) features without them feeling like bloat or being difficult to learn/understand.

**Comment by Joe23232** [comment]
Hi mate thanks for your response :)

3. In regards to this, wouldn't it be a bad idea to have reference counting at all cause it has an overhead? Cause Rust does it via the ownership model?

**Comment by ALANVF** [comment]
You would still have overhead if you had to use something like `Rc` in rust, right? The idea here is that ownership rules are always used unless they can't be applied, in which case RC is used instead. If the compiler can determine that an RCed value won't have any cycles, then normal ARC can be used instead of Nim's RC strategy (to reduce overhead). You should ideally *never* be forced to manually manage your memory in Star unless absolutely necessary, because the language is more than capable of handling itself

**Comment by Joe23232** [comment]
> You would still have overhead if you had to use something like Rc in rust, right?

Oh yes that is true man. But it is optional.

> The idea here is that ownership rules are always used unless they can't be applied, in which case RC is used instead.

> RCed value won't have any cycles, then normal ARC can be used instead of Nim's RC strategy (to reduce overhead). You should ideally never be forced to manually manage your memory in Star unless absolutely necessary

So by default does Star use ownership model by default?

**Comment by ALANVF** [comment]
Yes, Star will use ownership by default until it cannot be applied, in which case it switches to reference counting.

**Comment by Joe23232** [comment]
Sorry I am a bit of a noob when it comes to programming languages but in regards to Rust, don't you have to explicitly state that you want to use RC? So how would Star determine it can't use ownership?

**Comment by ALANVF** [comment]
Star determines that a value can't use ownership if the value violates the rules of ownership

**Comment by Joe23232** [comment]
So lets say if I do something like this.

```rust
// This is Rust
fn main()
{
let mut x = 10;
let y = &mut x;
let z = &mut x;

println!("{} {}", y, z);
}
```

I just violated the Rust's ownership rule as two mutable references are not allowed. So would Star also prevent me from doing this or would it use reference counting?

**Comment by ALANVF** [comment]
Theoretically it would switch to reference counting. However, Star doesn't have actual references like rust, so it wouldn't be possible in the first place

**Comment by Joe23232** [comment]
Oh, if it is a low level language may I know what was the reason behind not having references?

**Comment by ALANVF** [comment]
References would violate Star's rule of not special-casing builtin types (syntax & behavior), as well as complicate Star's memory management strategies

**Comment by Joe23232** [comment]
> References would violate Star's rule of not special-casing builtin types (syntax & behavior), as well as complicate Star's memory management strategies

Interesting. So what does it do instead then?

Is this a language that is suitable to create an operating system?

**Comment by ALANVF** [comment]
> Interesting. So what does it do instead then?

You either use pointers or a different coding strategy (keeping in mind that Star is pass-by-object). I've never been a huge fan of immutability and purity (especially in the world of FP), but one idea I've always liked is that side-effects should *always* be obvious. References kinda make that impossible, as you can take the reference of anything and do whatever you want with it. By not allowing references (like in Rust or C++), it eliminates a lot of painful debugging and errors that might have happened otherwise.

> Is this a language that is suitable to create an operating system?

Seeing how someone even made an operating system in Crystal, I don't see why not (although I can't be certain until I try it I suppose)

**Comment by Joe23232** [comment]
> You either use pointers or a different coding strategy (keeping in mind that Star is pass-by-object). I've never been a huge fan of immutability and purity (especially in the world of FP), but one idea I've always liked is that side-effects should always be obvious. References kinda make that impossible, as you can take the reference of anything and do whatever you want with it. By not allowing references (like in Rust or C++), it eliminates a lot of painful debugging and errors that might have happened otherwise.

I see mate, thank you :)

> Seeing how someone even made an operating system in Crystal, I don't see why not (although I can't be certain until I try it I suppose)

Interesting.

**Comment by ALANVF** [comment]
:+1:
