### ISSUE TITLE
Questions about Star

### ISSUE THREAD

**Issue by D0ctorWh0** [ALANVF/star#3]
Hi, your language looks nice.  May I ask some questions about it?

1. I installed an extension to highlight the Star syntax in VSCode and Haxe, but I don't know what to do with HashLink and how to run/compile Star code.
2. Will Star be able to use other libraries (C/.NET/...) in the future? Can I use Windows API for example?
3. Will other libraries (C/.NET/...) be able to use Star libraries in the future?

**Comment by ALANVF** [comment]
Hey there, I'm glad you like my language!

### 1
Depending on your computer, there's a few things you'll need to do for hashlink:
    - Clone the `star` branch of `ALANVF/hashlink`
    - On windows, you'll want to open up the solution file with some modern version of Visual Studio (I use 2019), and then build the solution. Make sure you've followed the instructions in the readme for setting up some of required modules
    - On linux, you'll want to run `make all`. Make sure you have the required modules installed
    - On mac os, uh, follow the default instructions for hashlink and hope it works lol (I don't have a mac to test it on)

Star does not run just yet, but the compiler is currently a work-in-progress right now. I've been working on the type-checker, which you can test by running `haxe build.hxml`. Just a note, there are lots error messages that come from the type-checking Star's stdlib because I haven't finished the typer yet. Will be fixed soon-ish.

### 2
Ideally C interop will be directly supported as a feature once Star is bootstrapped using LLVM (see `examples/LLVMC.star` for an extended example!). Interop with similar languages like Pascal and Fortran are also being considered.

C++ support would be nice, but is highly unlikely because of C++'s infamously unstandardized name mangling schemes.

Objective-C/Swift interop would be cool, but no guarantees.

I've considered .NET support because its object system works really well with Star's type system, but no promises as of now (because I don't even know how I would do such a thing).

### 3
Once Star is bootstrapped using LLVM, this should ideally be possible. I have already created [a draft PoC](https://github.com/ALANVF/Star-lang-specification/blob/master/design/ABI.md) in the specification repo for Star's ABI, taking some ideas from Swift's ABI to allow for complex mangled types and constraints.


If you'd like to ask me more about Star, feel free to send me an email or DM me on Discord at `theangryepicbanana#8297`!
